stages:
  - test

default:
  image: node:12.18-buster-slim
  before_script:
    - node --version
    - npm --version
    - whoami
    - apt-get update
    - apt-get install -y git
    - npm install

test:
  stage: test
  only:
    refs:
      - develop
      - merge_request
  script:
    - npm test
